### ISSUE TITLE
Eval on blank area

### ISSUE THREAD

**Issue by caodinhduc** [TencentARC/SGAT4PASS#1]
Hello, thank you for great work.
when you evaluate model, did you eval model on the area where the rgb image is blank?

**Comment by WuTao-CS** [comment]
We follow Trans4PASS. you can ref [this](https://github.com/TencentARC/SGAT4PASS/blob/ce6f572e91b9ca1f250a4bd8cbd3cadd70ed9b93/segmentron/utils/score.py#L91C40-L91C41)
