### ISSUE TITLE
Hi I have seen the Trans4pass and SGT4PASS there is no major difference can you please eleborate where you made changes to make the model spherical geometry aware network?

### ISSUE THREAD

**Issue by anamce** [TencentARC/SGAT4PASS#2]

**Comment by WuTao-CS** [comment]
Hello, Sorry for seeing your question late. Our work is based on Trans4PASS. There are three improvements in spherical geometry.

- The first is SGA Image Projection, which uses data expansion to let the network learn the rotation invariance of the sphere. 
- The second is SDPE, which adds the distortion law of spherical geometry to the deformable Patch Embedding for constraint. 
- The third is Panorama-aware Loss, which mainly simulates the information density distribution of the sphere. 

If you are interested in the details, you can check our paper for details.

**Comment by anamce** [comment]
Hi Sugar,

Thankyou for your response, I want to run that model on my custom dataset and m using map10to9 instead of colourtoindex mapping during dataset loading method when I run the model I get target and input batch size doesn’t match error .can you please let me know how to resolve that error?

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
