### ISSUE TITLE
Hi, after training the model by using Segformer pretrained weights how we can visualize the results RGB Vs gt Mask Vs predicted masks?

### ISSUE THREAD

**Issue by anamce** [TencentARC/SGAT4PASS#3]

**Comment by WuTao-CS** [comment]
Hello, we have implemented this function in [tools/eval_s2d3d_span.py](https://github.com/TencentARC/SGAT4PASS/blob/main/tools/eval_s2d3d_span.py). We only need to specify a save path (args.save-path) to visualize the results.
